//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

ActivityType = {
'NEW_VIDEO' : 1,
'NEW_USER' : 2,
'NEW_REPLAY' : 3,
'NEW_POST' : 4
};
Activity = function(args) {
  this.id = null;
  this.created_ts = null;
  this.type = null;
  this.description = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
    if (args.created_ts !== undefined) {
      this.created_ts = args.created_ts;
    }
    if (args.type !== undefined) {
      this.type = args.type;
    }
    if (args.description !== undefined) {
      this.description = args.description;
    }
  }
};
Activity.prototype = {};
Activity.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.created_ts = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.type = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.description = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Activity.prototype.write = function(output) {
  output.writeStructBegin('Activity');
  if (this.id) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.created_ts) {
    output.writeFieldBegin('created_ts', Thrift.Type.I64, 2);
    output.writeI64(this.created_ts);
    output.writeFieldEnd();
  }
  if (this.type) {
    output.writeFieldBegin('type', Thrift.Type.I32, 3);
    output.writeI32(this.type);
    output.writeFieldEnd();
  }
  if (this.description) {
    output.writeFieldBegin('description', Thrift.Type.STRING, 4);
    output.writeString(this.description);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

