//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

YoutubeVideo = function(args) {
  this.id = null;
  this.created_ts = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
    if (args.created_ts !== undefined) {
      this.created_ts = args.created_ts;
    }
  }
};
YoutubeVideo.prototype = {};
YoutubeVideo.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.created_ts = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

YoutubeVideo.prototype.write = function(output) {
  output.writeStructBegin('YoutubeVideo');
  if (this.id) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.created_ts) {
    output.writeFieldBegin('created_ts', Thrift.Type.I64, 2);
    output.writeI64(this.created_ts);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

