/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ActivityType implements org.apache.thrift.TEnum {
  NEW_VIDEO(1),
  NEW_USER(2),
  NEW_REPLAY(3),
  NEW_POST(4);

  private final int value;

  private ActivityType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ActivityType findByValue(int value) { 
    switch (value) {
      case 1:
        return NEW_VIDEO;
      case 2:
        return NEW_USER;
      case 3:
        return NEW_REPLAY;
      case 4:
        return NEW_POST;
      default:
        return null;
    }
  }
}
